[project]
name = "Detik.com-Scraping"
version = "1.0.0"
description = "Scraping data form Detik.com."
dependencies = [
    "flask",
]

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"